README.md
My thinking here is that people get the chance to get feedback before there would be some "hard decision" by an on chain vote.
=> Refine the process

0000-evidence-template.md
Fixes a typo in the evidence template.
=> chore: Fix evidence template typo

evidence/acatangiu/0001-acatangiu-2024-H1-evidence.md
Dear Fellows,
I am submitting this evidence covering my recent relevant activity in the Polkadot ecosystem, with the intention of retaining rank 2.
You can see the [rendered version here](https://github.com/acatangiu/Evidences/blob/main/evidence/acatangiu/0001-acatangiu-2024-H1-evidence.md).
Blake2-256 hash of the file: `71e08b12e9d8ad8cbab2a09a95349b7894bcdfe3b45e723f30e990739f46efc2`
=> acatangiu-2024-H1 evidence for retain rank 2

evidence/skunert/0001-skunert-retain-II-2024.md
Hey everyone,
I am submitting evidence here to retain my current rank II.
Hash: `abd60508482a3f5ecf69f8e23b3d18c04a182b083ce7d87d13ab02d9d7c2ab63`
How to verify using [blake2](https://crates.io/crates/blake2_bin):
```
blake2 -s --length 32 evidence/skunert/0001-skunert-retain-II-2024.md
```
Edit: Will resubmit evidence on-chain at a later point as indicated in https://github.com/polkadot-fellows/Evidences/pull/3
=> skunert - Retain Rank II Jan - May 2024

evidence/muharem/0001-muharem-05-2024-retantion-evidence.md
Here you can find my letter written as an evidence to retain at rank 2, where I share what I have been working since my previous report.
blake2 256 - `42224cc3d14f89574c601381b236fc82546f83579a8113762a5c96cd1a16e5fb`
verify with [b2sum](https://formulae.brew.sh/formula/b2sum):
```
b2sum -a blake2s -l 256 ./evidence/muharem/0001-muharem-05-2024-retantion-evidence.md 
```
=> muharem: retain at rank 2 evidence

evidence/doordashcon/0000-evidence-template.md, evidence/doordashcon/0001-doordashcon-2024-H1.md
Greetings,
I am presenting evidence here to maintain my current rank I.
You can view the rendered version [here](https://github.com/Doordashcon/Evidences/blob/ddc-evidence/evidence/doordashcon/0001-doordashcon-2024-H1.md)
Hash `0x28e1db12cff7513fc9b0fe9ae43818c577f644092fb5c27fc66b9b4ae15d66a6`
=> Doordashcon: Retain Rank I Jan - May 2024

evidence/xlc/2024-06-11.md
https://ipfs.io/ipfs/bafybeietyn52gq44qqgilkeona55mdqdh76w5dgsd4sc36zl56fuqxbspy
=> xlc: Retain at rank 4

evidence/koute/0001-koute-evidence-2024-05-09.md, evidence/koute/0001-koute-retain-II-2024.md
[Rendered](https://github.com/polkadot-fellows/Evidences/blob/a8fc017ffdd53a8c1665c46a5bed07999c3ff6ae/evidence/koute/0001-koute-retain-II-2024.md)
=> Add evidence: koute - promote to rank III, May 2024

evidence/wirednkod/0001-2024-05-evidence.md
Evidence [rendered](https://github.com/wirednkod/Evidences/blob/main/evidence/wirednkod/0001-2024-05-evidence.md)
=> wirednkod: retain at Rank I

evidence/rossbulat/0001-rossbulat-retain.md
Please find evidence in `evidence/rossbulat/0001-rossbulat-retain.md`.
=> rossbulat: retain at rank 1

evidence/ank4n/0001-ank4n-2024-H1.md
Submitting evidence to retain my rank I in Polkadot Technical Fellowship.
[IPFS link](https://ipfs.io/ipfs/bafybeidu5z73qaadwjohgtkbqsff5ixxa3b6hbgnmq3jd62gfklda24yjq)
=> [2024-H1] Retention at Rank I for `ank4n`

evidence/ordian/0001-retain-III-2024-H1.md
As a side note, I'm not planning to claim fellowship salary as long as I'm employed at Parity.
=> ordian: retain at rank III

evidence/liamaharon/0001-2024-05-evidence.md
[Rendered](https://github.com/liamaharon/Evidences/blob/main/evidence/liamaharon/0001-2024-05-evidence.md)
=> liamaharon: Retain at Rank 1

evidence/dharjeezy/0001-dharjeezy-07-2024-retention-evidence.md
My Evidence to retain rank I in Polkadot Technical Fellowship
[IPFS link](https://ipfs.io/ipfs/bafybeieyldr6ah2ncizkim4rw2bfn4n4gzlg5xla377fw2ktcfaahowkva)
=> dharjeezy: retain at rank I

evidence/serban300/0001-2024-H1-rank-1-retention.md
Evidence to support my retention at rank 1.
=> serban300: retain at rank 1

evidence/andresilva/0001-andresilva-2024-H1-evidence.md
[Rendered](https://github.com/polkadot-fellows/Evidences/blob/62420d90eaecd262dccce56fabc97cf0d2931226/evidence/andresilva/0001-andresilva-2024-H1-evidence.md)
=> andresilva: retain at rank 5

evidence/skunert/0002-skunert-retain-II-2024.md
Retention evidence from may - august
=> skunert: retain at rank II

evidence/pandres95/00001-2024-07-retain-rank-1.md
[Rendered document](https://github.com/polkadot-fellows/Evidences/blob/918c90b3ae9b23b77cca7999f2f5a8c3498ea86d/evidence/pandres95/00001-2024-07-retain-rank-1.md)
=> pandres95: Retention at Rank 1

evidence/cisco/0001-2024-08-14-rank-1-retention.md
[Rendered Document](https://github.com/franciscoaguirre/Evaluations/blob/main/evidence/cisco/0001-2024-08-14-rank-1-retention.md)
=> cisco: Retention at Rank 1

evidence/bkontur/0001-bkontur-2024-retention-rank1-evidence.md
[Rendered Document](https://github.com/bkontur/polkadot-fellows-evaluations/blob/bko-retention-rank1/evidence/bkontur/0001-bkontur-2024-retention-rank1-evidence.md)
=> bkontur: Retention at Rank 1

evidence/davxy/0002-davxy-2024-H2.md
Retention evidence from [Jun - Sep)
[Rendered](https://github.com/davxy/polkadot-fellows-evidences/blob/main/evidence/davxy/0002-davxy-2024-H2.md)
=> davxy: retain at rank II

evidence/athei/0001-retain-III.md
[Rendered Version](https://github.com/athei/Evaluations/blob/at/eval/evidence/athei/0001-retain-III.md)
=> athei: retain at rank III

evidence/joepetrowski/0001-2024-09-retention-rank-2.md, evidence/joepetrowski/0002-2024-09-retention-rank-2.md
Evaluation submission: https://collectives-polkadot.subscan.io/extrinsic/4629773-2
=> joepetrowski: Retain at Rank II

evidence/claravanstaden/0001-claravanstaden-2024-retention-rank-1.md
Please note, I already submitted this evidence on-chain. 🫣 Apologies, will do the next retention process in the correct order.
=> claravanstaden: Retain at Rank I

evidence/doordashcon/0002-doordashcon-08-2024.md
Retention evidence from [Jun - Aug]
[Rendered](https://github.com/Doordashcon/Evidences/blob/ddc-evidence-T2-I/evidence/doordashcon/0002-doordashcon-08-2024.md)
=> doordashcon: retain at rank I

README.md, faq.md
Link to FAQ to be added in the readme.
=> add FAQ about voting records and in-person interviews

evidence/edwardmack/0001-edwardmack-09-24-retention-evidence.md
Evidence to support my retention at rank 2.
=> edwardmack: retain at rank II

evidence/s0me0ne-unkn0wn/0002-20240927-retention.md
Rendered version: [evidence/s0me0ne-unkn0wn/0002-20240927-retention.md](https://github.com/s0me0ne-unkn0wn/Evaluations/blob/main/evidence/s0me0ne-unkn0wn/0002-20240927-retention.md)
=> s0me0ne-unkn0wn: retain at rank I

evidence/alin/0002-alin-retain-I-2024.md
[Rendered](https://github.com/alindima/Evidences/blob/alindima/evidence-2/evidence/alin/0002-alin-retain-I-2024.md)
=> alindima: retain at rank I

evidence/miszka/0001-miszka-retain-I-2024-10-02.md
My [evidence](https://github.com/michalkucharczyk/Evaluations/blob/mku-evidence-rank-I/evidence/miszka/0001-miszka-retain-I-2024-10-02.md) for retaining at rank 1.
=> miszka: retain at rank I

evidence/acatangiu/0003-acatangiu-2024-Q3-evidence.md
Dear Fellows, please find my rank `II` retention letter: [rendered version here](https://github.com/acatangiu/Evidences/blob/retention/evidence/acatangiu/0003-acatangiu-2024-Q3-evidence.md).
=> acatangiu: retain rank 2 - 2024 Q3

evidence/pandres95/00002-2024-10-retain-rank-1.md
[Rendered document](https://github.com/pandres95/Evidences/blob/4baeb1cde15a3dde6f0bf9fecde37470024ad26c/evidence/pandres95/00002-2024-10-retain-rank-1.md)
=> pandres95: retain at rank 1

evidence/georgepisaltu/0001-georgepisaltu-2024-Q3-rank1-retention.md
[Rendered version](https://github.com/georgepisaltu/Evaluations/blob/main/evidence/georgepisaltu/0001-georgepisaltu-2024-Q3-rank1-retention.md)
=> georgepisaltu: retain at rank 1

evidence/davxy/0003-davxy-2024.md
[Rendered](https://github.com/davxy/polkadot-fellows-evidences/blob/main/evidence/davxy/0003-davxy-2024.md)
=> davxy: retain at rank 2

evidence/ggwpez/87.md
[Rendered](https://github.com/polkadot-fellows/Evaluations/blob/0276b34b34bd9b9fe7c09af1e9b47cdad6f2a453/evidence/ggwpez/87.md)
Voting participation was checked with [this](https://github.com/ggwpez/substrate-scripts/blob/144a18ce76f8f643ebc2ce7f0a4053edbcbc6715/fellowship-voting-evidence.py) script: `python3 fellowship-voting-evidence.py --account 16a357f5Sxab3V2ne4emGQvqJaCLeYpTMx3TCjnQhmJQ71DX --endpoint "https://dotburned.squids.live/fellowship-votes@v1/api/graphql" -r 3`.
<details><summary>Output</summary>
<p>
```pre
✅ Ref 127 track  3, rank: 3, vote: Aye
✅ Ref 126 track 11, rank: 3, vote: Aye
✅ Ref 122 track 11, rank: 3, vote: Aye
✅ Ref 128 track  3, rank: 3, vote: Aye
✅ Ref 123 track 21, rank: 3, vote: Aye
✅ Ref 124 track 21, rank: 3, vote: Aye
✅ Ref 130 track  3, rank: 3, vote: …
```
=> Retention of Rank III

evidence/bkontur/0002-bkontur-2024-retention-rank1-evidence.md
[Rendered](https://github.com/bkontur/polkadot-fellows-evaluations/blob/bko-evidence-rank1-2024-11/evidence/bkontur/0002-bkontur-2024-retention-rank1-evidence.md)
=> bkontur: retain at rank1

evidence/ordian/0002-retain-III-2024-H2.md
[Rendered](https://github.com/polkadot-fellows/Evaluations/pull/93/files?short_path=472928e#diff-472928ef95c388cf2b1b7d6f214000c8203a804838b031f5e042f80e491f8a59)
=> ordian: retain at rank 3

evidence/claravanstaden/0001-claravanstaden-2024-02-retention-rank-1.md, evidence/claravanstaden/0002-claravanstaden-2024-02-retention-rank-1.md
Dear fellows, please evaluate my application to be retained at rank 1 ([rendered](https://github.com/claravanstaden/Evaluations/blob/main/evidence/claravanstaden/0002-claravanstaden-2024-02-retention-rank-1.md)).
=> claravanstaden: retain at rank 1

evidence/s0me0ne-unkn0wn/0003-20241217-retention.md
Rendered: https://github.com/s0me0ne-unkn0wn/Evaluations/blob/s0me0ne/retention-I-20241217/evidence/s0me0ne-unkn0wn/0003-20241217-retention.md
=> Retention at rank I

evidence/koute/0002-koute-evidence-2025-01-06.md
[Rendered](https://github.com/polkadot-fellows/Evaluations/blob/a63502cc8998945d96c058ad6423f1de89d3de83/evidence/koute/0002-koute-evidence-2025-01-06.md)
=> koute: retain at rank 3

evidence/mrshiposha/0001-promotion-rank-1.md
[The rendered document](https://github.com/polkadot-fellows/Evaluations/blob/f30ce69c4f1dcbe2fe5f8901039a1d113b88a077/evidence/mrshiposha/0001-promotion-rank-1.md)
=> mrshiposha: promotion to Rank 1

evidence/alexggh/0002-2025-01-20-rank-1-retention.md
[Rendered](https://github.com/alexggh/Evaluations/blob/alexggh-retain-2025-01-20/evidence/alexggh/0002-2025-01-20-rank-1-retention.md)
IPFS: https://subsquare.infura-ipfs.io/ipfs/bafybeic5wqadvmpmie7asva3tbte2a2egynmfjr5bawsiuwv3vrqse7zjm
=> [2025-01-20] alexggh retain at rank 1

evidence/skunert/0004-skunert-retain-II-2025.md
Here is my evidence for retention at rank 2
=> skunert: retain at rank 2

evidence/cisco/0003-2025-02-13-rank-1-retention.md
[Rendered document](https://github.com/franciscoaguirre/Evaluations/blob/main/evidence/cisco/0003-2025-02-13-rank-1-retention.md)
=> cisco: retain at rank 1

evidence/bkontur/0003-bkontur-2025-retention-rank1-evidence.md
[Rendered](https://github.com/bkontur/polkadot-fellows-evaluations/blob/bko-evidence-rank1-2025-02/evidence/bkontur/0003-bkontur-2025-retention-rank1-evidence.md)
=> bkontur: retain at rank1 evidence

0000-argument-template.md, README.md, evidence/s0me0ne-unkn0wn/0004-20250319-retention.md, faq.md
[Rendered](https://github.com/s0me0ne-unkn0wn/Evaluations/blob/main/evidence/s0me0ne-unkn0wn/0004-20250319-retention.md)
=> Retention evidence

evidence/mrshiposha/0002-retention-rank-1.md
[Rendered](https://github.com/polkadot-fellows/Evaluations/blob/b90f003041083a0977e18198b8345ac9faea4e1c/evidence/mrshiposha/0002-retention-rank-1.md)
=> mrshiposha: Retain Rank I

evidence/gui/0002-rank-1-retention.md
here is my argument for retention at rank I
=> Retention at Rank I: Gui

evidence/clangenb/0004-retention-rank-1-202504.md
[Rendered](https://github.com/polkadot-fellows/Evaluations/blob/344ba2af3a17689310642401140f6ffb295b0f7b/evidence/clangenb/0004-retention-rank-1-202504.md)
=> clangenb: Retention at Rank 1

evidence/alexggh/0003-2025-04-20-rank-1-retention.md
[Rendered version](https://github.com/alexggh/Evaluations/blob/alexggh/evaluation/evidence/alexggh/0003-2025-04-20-rank-1-retention.md)
=> [2025-04-19] alexggh retain at rank 1

evidence/tdimitrov/0003-rank2-promotion-feb2025.md
[Rendered](https://github.com/tdimitrov/Evidences/blob/rank2-promotion-feb-2025/evidence/tdimitrov/0003-rank2-promotion-feb2025.md)
=> tdimitrov: Promotion to rank 2

evidence/dharjeezy/0004-dharjeezy-04-2025-retention-evidence.md
[Rendered](https://github.com/dharjeezy/Evidences/blob/dami/evidence-4/evidence/dharjeezy/0004-dharjeezy-04-2025-retention-evidence.md)
=> dharjeezy: retain at rank 1

evidence/muharem/0005-muharem-05-2025-retantion-evidence.md
[Rendered](https://github.com/muharem/polkadot-fellows-evidences/blob/muharem-evidence-letter-5/evidence/muharem/0005-muharem-05-2025-retantion-evidence.md) version.
=> muharem: retain at rank 2

evidence/davxy/0005-davxy-2025.md
[RENDERED](https://github.com/davxy/polkadot-fellows-evaluations/blob/davxy/retain/evidence/davxy/0005-davxy-2025.md)
=> davxy: retain rank 2

evidence/sandreim/0004-sandreim-retain-2025.md
[Rendered version](https://github.com/polkadot-fellows/Evaluations/blob/a193905085bc4e6db58986611216c4aa691249c0/evidence/sandreim/0004-sandreim-retain-2025.md)
=> sandreim: Retain at Rank III 

evidence/polkadotdom/0001-rank1-promotion.md
[Rendered](https://github.com/PolkadotDom/Evaluations/blob/dom/promotion-rank-1/evidence/polkadotdom/0001-rank1-promotion.md)
=> polka.dom - promotion to rank 1

evidence/skunert/0006-skunert-promote-III-2025.md
Please find in this PR my wish for promotion to rank III of the fellowship.
=> skunert: Promote to rank III

evidence/gui/0003-rank-1-retention.md
this is my evidence for retention, I have less than 14 days left of my demotion period.
=> gui retention rank 1

evidence/alexggh/0005-2025-09-05-rank-2-promotion.md
[Rendered](https://github.com/alexggh/Evaluations/blob/alexggh-promote-rank-2/evidence/alexggh/0005-2025-09-05-rank-2-promotion.md)
=> alexggh: promote to rank 2

evidence/bkontur/0006-bkontur-2025-retention-rank2.md
[Rendered](https://github.com/bkontur/polkadot-fellows-evaluations/blob/bko-arugment-retention-rank2-2025-10/evidence/bkontur/0006-bkontur-2025-retention-rank2.md)
=> bkontur: argument for retention rank2
